[tool.black]
line-length = 88
target-version = ['py311']

[tool.mypy]
files = "src"
strict = true
ignore_missing_imports = true

[tool.isort]
profile = "black"

[tool.pytest]
testpaths = [ "src/tests" ]
