name: PR and Push Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  run-check-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-24.05

      - name: Run lint check script in Nix shell
        run: |
          cd \"$GITHUB_WORKSPACE\"
          echo 'Current directory: $(pwd)'
          echo 'Contents:'
          ls -R
          nix develop -c "
            set -e
            echo 'Entered Nix shell'
            echo 'Running check script'
          "
