name: PR and Push Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  run-nix-develop-and-lint:
    name: Run nix develop and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-24.05

      - name: Enter Nix Shell
        run: nix develop

      - name: Run check script
        run: ./scripts/check.sh
